return {
    { src = 'https://github.com/neovim/nvim-lspconfig' },
    { src = 'https://github.com/mason-org/mason.nvim' },
    { src = 'https://github.com/stevearc/oil.nvim' },
     { src = 'https://github.com/stevearc/conform.nvim' },
    { src = 'https://github.com/nvim-treesitter/nvim-treesitter', version = 'main' },
    { src = 'https://github.com/folke/lazydev.nvim' },
    { src = 'https://github.com/nvim-telescope/telescope.nvim' },
    { src = 'https://github.com/nvim-lua/plenary.nvim' },
    { src = 'https://github.com/folke/which-key.nvim' },
    { src = 'https://github.com/MagicDuck/grug-far.nvim' },
    { src = 'https://github.com/mfussenegger/nvim-jdtls' },
    { src = 'https://github.com/airblade/vim-gitgutter' },
    { src = 'https://github.com/nickjvandyke/opencode.nvim' },
    { src = 'https://github.com/github/copilot.vim' },
    { src = 'https://github.com/sindrets/diffview.nvim' },
    { src = 'https://github.com/nvim-tree/nvim-web-devicons' },
}
